<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<link rel="shortcut icon" href="<?=$siteurl?>/assets/img/favicon.ico"/>
		<base href="<?=$siteurl?>/admin/">
		<title><?=$page?> - Admin Dashboard</title>
		<link href="css/app.css" rel="stylesheet" />
		<link href="css/pace-theme.css" rel="stylesheet" />
		<link rel="stylesheet" type="text/css" href="css/ldbtn.min.css">
		<link rel="stylesheet" type="text/css" href="css/ld-loading.min.css">
		<style type="text/css">
			.align-center{
				text-align: center;
			}
			.fe-custom {
				width: 20px!important;
				height:20px!important;
				stroke: currentColor;
				stroke-width: 2;
				stroke-linecap: round;
				stroke-linejoin: round;
				fill: none;
			}
			.form-group:not(.stop)>label {
				top: 18px;
				left: 6px;
				position: relative;
				background-color: white;
				padding: 0px 5px 0px 5px;
				font-size: 0.9em;
			}
			.form-group>.form-control {
				display: block;
			    width: 100%;
			    height: 45px;
			    padding: 10px 15px;
			    font-size: 15px;
			    line-height: 1.42857143;
			    border: 1px solid #dce4ec;
		        border-radius: 4px;
		        border-width: 2px;
			}

		    .radio-success .custom-control-input:checked~.custom-control-label:before {
		        color: #fff;
		        border-color: #5cb85c;
		        background-color: #5cb85c;
		    }
		    .radio-danger .custom-control-input:checked~.custom-control-label:before {
		        color: #fff;
		        border-color: #d9534f;
		        background-color: #d9534f;
		    }

		    .p-img {
		    	height: 5rem;
		    	width: 5rem;
		    }
		</style>

		<script src="js/jquery.min.js"></script>
	</head>

	<body>
		<div class="wrapper">