<nav id="sidebar" class="sidebar">
	<div class="sidebar-content js-simplebar">
		<a class="sidebar-brand" href="<?=$siteurl?>">
			<span class="align-middle"><?=$sitename?></span>
		</a>

		<ul class="sidebar-nav">
			<li class="sidebar-header">Main</li>

			<li class="sidebar-item active">
				<a class="sidebar-link lazy" href="./"> 
					<i class="align-middle" data-feather="sliders"></i> 
					<span class="align-middle">Dashboard</span> 
				</a>
			</li>

			<li class="sidebar-header">Mailings</li>
			<li class="sidebar-item">
				<a class="sidebar-link lazy" href="./emails"> 
					<i class="align-middle" data-feather="mail"></i> 
					<span class="align-middle">Sent emails</span> 
				</a>
			</li>
			<li class="sidebar-item">
				<a class="sidebar-link lazy" href="./generate"> 
					<i class="align-middle" data-feather="code"></i> 
					<span class="align-middle">Generate Code</span> 
				</a>
			</li>
			<li class="sidebar-item">
				<a class="sidebar-link lazy" href="./send"> 
					<i class="align-middle" data-feather="send"></i> 
					<span class="align-middle">Send Email</span> 
				</a>
			</li>
			
			<li class="sidebar-header">Site</li>
			<li class="sidebar-item">
				<a class="sidebar-link lazy" href="./settings"> <i class="align-middle" data-feather="settings"></i> <span class="align-middle">Site Settings</span> </a>
			</li>
			<li class="sidebar-item">
				<a class="sidebar-link lazy" href="./email-themes"> <i class="align-middle" data-feather="layout"></i> <span class="align-middle">Email Themes</span> </a>
			</li>
			<li class="sidebar-item">
				<a class="sidebar-link lazy" href="./email-templates"> <i class="align-middle" data-feather="layers"></i> <span class="align-middle">Email Templates</span> </a>
			</li>
			<li class="sidebar-item">
				<a class="sidebar-link" target="_blank" href="<?=$siteurl?>/docs"> <i class="align-middle" data-feather="book"></i> <span class="align-middle">Documentation</span> </a>
			</li>
		</ul>

	</div>
</nav>